### ISSUE TITLE
Is it possible to put this package on maven?

### ISSUE THREAD

**Issue by mrmechko** [gangeli/CoreNLP-Scala#3]
The `makefile` leads me to believe that it would be a substantial amount of work to do this, but if you could point me in the right direction, I'd be happy to take on the task of preparing the package for maven.

**Comment by gangeli** [comment]
I'm not at all opposed to the package being put up on Maven, though I'll admit it's not exactly a high priority for me currently. If you're willing to volunteer, go for it :). 

In part this is because I've been planning on deprecating the project in general in favor of a simple interface in CoreNLP itself (with Java 8 functions, this becomes much more):

https://github.com/stanfordnlp/CoreNLP/tree/master/src/edu/stanford/nlp/simple

**Comment by mrmechko** [comment]
The new code in CoreNLP looks good.  I might use it going forward, though I have a bunch of existing code which depends on this package. It seems the new code you referenced is (almost?) interchangeable with this package for the most part?  Either way, makes maven overkill for my purposes.

I added the requisite line to `build.sbt` to allow local publishing, which is sufficient for me. [This repository](http://www.github.com/mrmechko/senseval2) uses the locally published version, both on my machine and on [travis-ci](http://www.travis-ci.org/mrmechko/senseval2).

**Comment by gangeli** [comment]
Sounds good; request pulled! And yes, in theory the code in CoreNLP should be nearly backwards compatible with the code here, at least in functionality. If it's not, let me know and I can probably add anything that's missing.
